### ISSUE TITLE
Throttle requests for "More Thumbs" hath perk

### ISSUE THREAD

**Issue by bossanovaorca** [FlandreDaisuki/My-Browser-Extensions#10]
is it possible to throttle the requests for the "More Thumbs" infinite scrolling hath perk? Sometimes when the page fails to load thumbnails, the script will send out requests to fetch subsequent pages extremely quickly, leading to a temporary IP ban

**Comment by FlandreDaisuki** [comment]
ok, this make sense!
I'll fix it as soon as possible.

**Comment by FlandreDaisuki** [comment]
resolve by be25fa0 in version 2.2.1

**Comment by bossanovaorca** [comment]
thank you so much for the quick fix!
