### ISSUE TITLE
和今天诈尸的E-Hentai Highlighter有小冲突

### ISSUE THREAD

**Issue by SJH114488406** [FlandreDaisuki/My-Browser-Extensions#2]
今天E-Hentai Highlighter竟然更新了，高亮效果不错，但是只能用官方tag flagging，和您的脚本一起装，他会无法自动激活，要点一下相关的按钮才能显示，作者有没有打算跟进一下，囊括一下他的功能？

**Comment by mo-han** [comment]
把 E-Hentai Highlighter 的脚本结尾改成这样：
```javascript
window.addEventListener('load', function() {
    // your code here
    EHH.init();
}, false);
```
这段代码表示一直等到标签页完成加载动作（包括原始页面和其他脚本），之后，再执行`EHH.init()`。这样可以确保 E-Hentai Highlighter 的主函数是最后执行的，就可以把其他脚本覆盖掉了。

我用的 Firefox + Tampermonkey，成功了。我是把 UHP 的 Tag Flagging 关掉的，只用了 E-Hentai Highlighter 的高亮。

我不会玩JS，这段代码的思路是从网上搜来的：
https://stackoverflow.com/questions/12897446/userscript-to-wait-for-page-to-load-before-executing-code-techniques

**Comment by FlandreDaisuki** [comment]
site updated
