### ISSUE TITLE
Tag Flagging & Remove Tag Hidden 

### ISSUE THREAD

**Issue by on1no** [FlandreDaisuki/My-Browser-Extensions#4]
Hi
And Sorry For My Bad English

Unlock Hath Perks v2.0.1

Can you Please Add : Tag Flagging & Remove Tag Hidden..

Please :)
![canvas](https://user-images.githubusercontent.com/35997957/56168705-9e07bc00-5fe4-11e9-8528-5ca1012b6819.png)

**Comment by FlandreDaisuki** [comment]
I implemented "Tag Flagging" because it needed to spend hath to unlock in Hath Perks before.
Now, this function opens to everyone in [e-hentai.org/mytags](https://e-hentai.org/mytags) and [exhentai.org/mytags](https://exhentai.org/mytags).

The official one is faster and better than I did.
