### ISSUE TITLE
UnlockHathPerks may need an update

### ISSUE THREAD

**Issue by bossanovaorca** [FlandreDaisuki/My-Browser-Extensions#8]
now that search results and paging has changed on E-H, this script might need updating to get infinite scrolling etc.

**Comment by FlandreDaisuki** [comment]
OK, I'll do my best ASAP.

**Comment by FlandreDaisuki** [comment]
Update in [2.1.0](https://github.com/FlandreDaisuki/My-Browser-Extensions/commit/124040a1cbc38e2a7915d0cf0a69052733c002cb)

**Comment by bossanovaorca** [comment]
thank you for the quick update
