### ISSUE TITLE
ExAdvancedSearchMemo Feature request, search term list

### ISSUE THREAD

**Issue by alidan** [FlandreDaisuki/My-Browser-Extensions#9]
The new update to ex broke a script I use to use daily called exviewer
https://sleazyfork.org/en/scripts/376340-exhentai-viewer
The main thing that I used it for was to quickly search for various terms, lets say if I wanted to search for something english, cream pie, and monster girl, instead of needing to have already searched for them and adding them like memo needs, I just save the terms and hit the ones I want, in this case it would show up like this
"English""monster girl""nakadashi"

im wondering if it would be possible to add this functionality to memo?
As it stands, I dont think the old script is going to be updated, and thank you reguardless as memo does about 90% of what I want, this is just quality of life.

**Comment by FlandreDaisuki** [comment]
First of all, I'm appreciate that you use my new userscript.

I just browse the script you provided, that is a great work for who always find galleries with different tags combination. However, that is not the similar to my usage habits on eh. On the other hand, combing separate tags and unified advance search in that small space is hard to do with good UX (everyone is aware of the importance of UX after the recent pagination disaster).

So, I just modify the original script and works fine with my userscripts.
https://gist.github.com/FlandreDaisuki/2823d20df9876f296c3cac96c05b39f5

**Comment by alidan** [comment]
Thankyou

Now I have to figure out how to add a space in between search terms as the new way ex works doesn't like "english""-nakadashi" as an example but will take "english" "-nakadashi" 

It always bugged me but because it worked I never thought to much of it. again thankyou for getting this to work.

**Comment by FlandreDaisuki** [comment]
@alidan I fixed this in v0.53.2 😎
